python main.py AAPL
python main.py ACN
python main.py ADBE
python main.py ADI
python main.py ADSK
python main.py AKAM
python main.py AMAT
python main.py AMD
python main.py ANSS
python main.py APH
python main.py AVGO
python main.py CDNS
python main.py CDW
python main.py CRM
python main.py CSCO
python main.py GLW
python main.py GPN
python main.py HPE
python main.py HPQ
python main.py IBM
python main.py INTC
python main.py INTU
python main.py IPGP
python main.py IT
python main.py KEYS
python main.py LRCX
python main.py MA
python main.py MCHP
python main.py MPWR
python main.py MSFT
python main.py MSI
python main.py MU
python main.py MXIM
python main.py NLOK
python main.py NTAP
python main.py NVDA
python main.py NXPI
python main.py ORCL
python main.py PYPL
python main.py QCOM
python main.py QRVO
python main.py SNPS
python main.py STX
python main.py TEL
python main.py TRMB
python main.py TXN
python main.py V
python main.py WDC
python main.py WU
python main.py XLNX

pause