python pretrain.py AAPL
python pretrain.py ACN
python pretrain.py ADBE
python pretrain.py ADI
python pretrain.py ADSK
python pretrain.py AKAM
python pretrain.py AMAT
python pretrain.py AMD
python pretrain.py ANSS
python pretrain.py APH
python pretrain.py AVGO
python pretrain.py CDNS
python pretrain.py CDW
python pretrain.py CRM
python pretrain.py CSCO
python pretrain.py GLW
python pretrain.py GPN
python pretrain.py HPE
python pretrain.py HPQ
python pretrain.py IBM
python pretrain.py INTC
python pretrain.py INTU
python pretrain.py IPGP
python pretrain.py IT
python pretrain.py KEYS
python pretrain.py LRCX
python pretrain.py MA
python pretrain.py MCHP
python pretrain.py MPWR
python pretrain.py MSFT
python pretrain.py MSI
python pretrain.py MU
python pretrain.py MXIM
python pretrain.py NLOK
python pretrain.py NTAP
python pretrain.py NVDA
python pretrain.py NXPI
python pretrain.py ORCL
python pretrain.py PYPL
python pretrain.py QCOM
python pretrain.py QRVO
python pretrain.py SNPS
python pretrain.py STX
python pretrain.py TEL
python pretrain.py TRMB
python pretrain.py TXN
python pretrain.py V
python pretrain.py WDC
python pretrain.py WU
python pretrain.py XLNX

pause